services:
  api:
    build: .
    container_name: api-reservas-springboot
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bd_reservas_hotel
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: postgres_db_reservas_habitacion
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bd_reservas_hotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bd_reservas_hotel"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: