spring:
  sql:
    init:
      mode: always
  application:
    name: API-Reservas

  datasource:
    url: ${SUPABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: UnaClaveSecretaLargaYSeguraParaFirmarElTokenQueSoloElServidorConoce1234567890
  expiration: 900000
  refrestToken: 86400000
